# Generated by Django 6.0.7 on 2026-07-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(default='Disponible', max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('responsable', models.CharField(blank=True, max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
    ]
