# Generated by Django 6.0.7 on 2026-08-03 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Prestado', 'Prestado'), ('En mantenimiento', 'En mantenimiento'), ('Dado de baja', 'Dado de baja'), ('En uso', 'En uso')], default='Disponible', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida'), ('Préstamo', 'Préstamo'), ('Devolución', 'Devolución'), ('Cambio responsable', 'Cambio responsable'), ('Cambio ubicación', 'Cambio ubicación'), ('Mantenimiento', 'Mantenimiento'), ('Dado de baja', 'Dado de baja')], max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('responsable_anterior', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_nuevo', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion_anterior', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion_nueva', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.equipo')),
            ],
        ),
    ]
