# Generated by Django 6.0.7 on 2026-08-06 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_categoria_marca_responsable_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(default='Sin modelo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
