# Generated by Django 6.0.7 on 2026-08-06 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_equipo_fecha_registro_equipo_modelo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo')], max_length=20)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20)),
                ('fecha', models.DateField()),
                ('tecnico', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='inventario.equipo')),
            ],
        ),
    ]
