# Generated by Django 6.0.7 on 2026-08-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
