# Generated by Django 6.0.7 on 2026-08-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_equipo_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='categoria_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='categoria_nueva',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='marca_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='marca_nueva',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='modelo_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='modelo_nuevo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='serial_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='serial_nuevo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
