# Generated by Django 6.0.7 on 2026-08-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_movimiento_categoria_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='horas_ultimo_mantenimiento',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='horas_uso',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='intervalo_mantenimiento',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
