# Generated by Django 6.0.7 on 2026-08-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_equipo_horas_ultimo_mantenimiento_equipo_horas_uso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='cantidad_mantenimientos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
